project_name: NengoExamples
pkg_name: nengo_examples
repo_name: nengo/nengo-examples

copyright_start: 2016
description: Examples using parts of the Nengo ecosystem

contributing_rst: {}

contributors_rst: {}

docs_conf_py:
  output_name: conf.py
  tagmanager_id: GTM-KWCR2HN

setup_cfg:
  pylint:
    disable:
      - broad-except
      - consider-using-f-string
      - function-redefined
      - redefined-outer-name
  codespell:
    ignore_words:
      - alha

setup_py: {}

travis_yml:
  python: 3.9
  jobs:
    - script: static

ci_scripts:
  - template: static

pre_commit_config_yaml: {}

pyproject_toml: {}

version_py:
  type: calver
  release: false
