project_name: NengoExamples
pkg_name: nengo_examples
repo_name: nengo/nengo-examples

copyright_start: 2016
description: Examples using parts of the Nengo ecosystem

contributing_rst: {}

contributors_rst: {}

setup_cfg:
  pylint:
    disable:
      - broad-except
      - consider-using-f-string
      - function-redefined
      - redefined-outer-name
  codespell:
    ignore_words:
      - alha

pre_commit_config_yaml: {}

pyproject_toml: {}
